### ISSUE TITLE
Function getCalendar : add controls

### ISSUE THREAD

**Issue by baptsegu** [rte-antares-rpackage/flowBasedClustering#12]
Return error if `interSeasonBegin `/ `interSeasonBegin` are not included in `dates`.
Return error if `interSeasonBegin `/ `interSeasonBegin` are empty.
Return error if `dates` - `dayExclude` is empty.

**Comment by TitouanRobert** [comment]
C'est fait pour les deux premiers. Pour le dernier cas j'ai préféré ajouter un warning : 
    warning("One (or more) period defined is empty. Process like clusteringTypicalDays can't be run")
L'idée ici c'est de pouvoir laisser le choix à l'utilisateur de définir des périodes vides mais de le prévenir que ça peu entrainer des problèmes pour la suite (je préfère un warning qu'une erreur bloquante). Qu'en penses-tu?
