### ISSUE TITLE
clusteringTypicalDays() returns an error 

### ISSUE THREAD

**Issue by baptsegu** [rte-antares-rpackage/flowBasedClustering#13]
The following code : 

```
dates <- getSequence("2015-11-01", "2017-01-20")
interSeasonBegin <- c("2016-03-01", "2016-10-01")
interSeasonEnd <- c("2016-05-15", "2016-10-31")
calendar <- getCalendar(dates, interSeasonBegin, interSeasonEnd)

vertices <- ptdfToVertices(PTDF = "inst/dev/data/faceAllYear.csv", nbCore = 4)
clusterTD <- clusteringTypicalDays(calendar, vertices, nbClustWeek = 3)
     
```

returns the followig error : 

` Error in combn(unique(vertices$Date), 2) : n < m `

**Comment by baptsegu** [comment]
After discussion with @TitouanRobert.
This error is due to a column format and can be bypassed with : 

```
re <- unlist(lapply(strsplit(vertices$Date, "/"), function(X){
  paste0(X[3], "-", X[2], "-", X[1])
}))
vertices$Date <- re
```

This error should be clarified with an appropriate message indicating : 
 * which column does not have the expected format
 * what is the expected format (here : %Y-%m-%d)

**Comment by TitouanRobert** [comment]
2 controls add, one format of date and the other on intersection between calandar vector of dates and vertices dates (stop job if one is empy).
