### ISSUE TITLE
clusteringTypicalDay report 

### ISSUE THREAD

**Issue by baptsegu** [rte-antares-rpackage/flowBasedClustering#16]
Add a first page with : 
 * The type of day corresponding to the typical day of the report (e.g. winter working day)
 * The historical dates whose belong to the cluster (with - in bold - the representant of the cluster)

**Comment by baptsegu** [comment]
Add in the name of the report the class of the typical day (interSeasonWe, winterWd, ...)

If it allows to reduce significantly the size of the report (for now, one report for one typical day sizes around 12Mo), delete the dynamic graphs and let only the static ones.

The static graphs are not displayed on (mine?) chrome navigator.

@MarionLi0 : anything to add ?

**Comment by MarionLi0** [comment]
Add a first tab displaying the class of the typical day and general information such as the number of days in the cluster, the mean and max distance to the typical day

Change the color of the background of the graphs, keep it white.

**Comment by TitouanRobert** [comment]
Done, i let issue open if you have feedback.

**Comment by MarionLi0** [comment]
Change the name of the csv from cluster.csv into cluster_typicalDay<Hour>.csv
Add "hour" in the tablets names for it not to be mistaken with the number of the typical day

**Comment by TitouanRobert** [comment]
Ok, done
