### ISSUE TITLE
Ids of typical days

### ISSUE THREAD

**Issue by MarionLi0** [rte-antares-rpackage/flowBasedClustering#18]
Keep the former ids for typical days:
1,2,3 summer week days
4 summer we
5,6,7 winter week days
8 winter we
9,10,11 interseason week days
12 interseason we

**Comment by TitouanRobert** [comment]
It's possible to chose the number of days in each period. I can do a control if we are in default situation and apply your processing?

**Comment by MarionLi0** [comment]
Maybe just keep the same order and it will only shift the numbers:
summer WDay
summer WEnd
winter WD
winter WE
interseason WD
interseason WE

**Comment by TitouanRobert** [comment]
Done
