### ISSUE TITLE
add a subset function of clusteringTypicalDays()

### ISSUE THREAD

**Issue by baptsegu** [rte-antares-rpackage/flowBasedClustering#19]
`clusterTypicalDaysForOneClass()` with in input : 

- `className `: name of the class
- `dates `: vector of dates
- `vertices `: data.table of vertices containing at least the one of the dates in dates
- `nbCluster`
- `report`
- `reportPath`
- `hourWeight`
- `id_start`

This function performs only one clustering on the domains given in `dates`

in output, the same type of data.table and report as `clusteringTypicalDays()`

**Comment by baptsegu** [comment]
MAJ de la doc.

Titouan pourrais tu en plus : 
- Ajouter un test avec comparaison des résultats de `clusteringOneTp `et `clusteringTypicalDays`.
- Ajouter un exemple dans la doc avec deux exécutions de `clusteringOneTp ` pour deux classes différentes (par exemple, avec `className = "january"` et `className = "february"`) et ensuite agréger les résultats dans un même data.table avec un `rbind`

**Comment by TitouanRobert** [comment]
Fait dans le commit de l'issue #38 a285b64a

**Comment by baptsegu** [comment]
Rajouter le test #38 qui pour le moment ne fonctionne pas et corriger

**Comment by TitouanRobert** [comment]
Ajout du test  : 
`
  expect_true(identical(out[idDayType == 4] ,  clusterTD[idDayType == 4]))
  expect_true(identical(out[idDayType == 5] ,  clusterTD[idDayType == 5]))
`
Ok avec la nouvelle modification

**Comment by baptsegu** [comment]
perfect
