### ISSUE TITLE
clusteringTypicalDays : return csv file readable by antaresFlowbased::computeFB()

### ISSUE THREAD

**Issue by baptsegu** [rte-antares-rpackage/flowBasedClustering#20]

**Comment by TitouanRobert** [comment]
Un info manque dans clusteringTypicalDays, nous ne disposons plus de PTDF (nous avons déjà utilisé ptdfToVertices à ce niveau).

**Comment by baptsegu** [comment]
Dans ce cas, créer une fonction avec en argument un cluster TD et un fichier de PTDF est en sortie le fichier csv en question

**Comment by TitouanRobert** [comment]
Function createPtdfForCompute

**Comment by baptsegu** [comment]
Test OK, serait-il possible de : 
- mette à jour le nom de la fonction `writePtdfOfTypicalDays()`
- retourner un csv avec séparateur `;` pour ouverture dans xcel

**Comment by TitouanRobert** [comment]
Passer en argument le séparateur

**Comment by baptsegu** [comment]
ok
