### ISSUE TITLE
getProbability() : deal with cases without historical records

### ISSUE THREAD

**Issue by baptsegu** [rte-antares-rpackage/flowBasedClustering#22]
For now, `getProbability()` returns `NA `when one combination of variables does not appear in historical data.

Add an argument to the function, named `extrapolationNA ` with default value `TRUE`.

if `extrapolationNA = TRUE`, `NA `should be replaced.

Example with NA : 
```
      Class TypicalDay idDayType fr/load DE_wind DE_solar Proba effectifClass
1: winterWd 2015-12-10         6  I0.333  I0.333   I0.333    NA             0
2: winterWd 2016-02-17         7  I0.333  I0.333   I0.333    NA             0
3: winterWd 2016-02-25         8  I0.333  I0.333   I0.333    NA             0
```

First, identify the neighbours of the situations without records. In the following example, there is three neighbours (B0.333&0.666, I0.333, I0.333), ( I0.333, B0.333&0.666, I0.333),  ( I0.333,  I0.333, B0.333&0.666).

* If strictly more (`>`) than 1/3 of neighbours are themselves without historical record (`effectifClass == 0`), then `NA `should be replaced by an equiprobable repartition (here **1/3** for each of the **3** typicalDay)

* If more(`>=`) than 2/3 of neighbours have a historical record (`effectifClass > 0`), then new probabilities are computed as the average of the probabilities of those neighbours.

@MarionLi0 could you please check :D

**Comment by TitouanRobert** [comment]
I propose you to add a message before extrapolation : 
68.1% of value extrapolate

**Comment by baptsegu** [comment]
It's a good idea, maybe with a warning : 
`warning : due to lack of historical record, XX % of the probability matrix has been extrapolated`

**Comment by TitouanRobert** [comment]
Done, we maybe should add a test for this part.

**Comment by baptsegu** [comment]
I check and everything seems OK.
An automatic test should be added

**Comment by baptsegu** [comment]
I add some tests in : https://github.com/rte-antares-rpackage/flowBasedClustering/blob/master/tests/testthat/test-probabilityMatrix.R

@TitouanRobert, if you have any other idea, do not hesitate to add a test.

Otherwise, you can close the issue.

**Comment by TitouanRobert** [comment]
Une interrogation sur l'interpolation : Faut-il pondérer notre moyenne de proba par l’effectif des classes du tableau?

**Comment by baptsegu** [comment]
On laisse comme c'est actuellement, moyenne non pondérée par les effectifs.
