### ISSUE TITLE
getProbability() : names of output data.table lacks of uniformity

### ISSUE THREAD

**Issue by baptsegu** [rte-antares-rpackage/flowBasedClustering#30]
Names sometimes start with a capital letter, sometimes with a lowercase letter (e.g. `Class` and `idDayType`).
Names are sometimes in English, sometimes in French (e.g. `effectifClass` and `TypicalDay`).

Proposition : all the names should start with a lower case and be in english.

`names(probMatrix[[1]]) `
* class
* typicalDay
* idDayType
* probability
* nbDaysInClass

`names(probMatrix[[2]])`
* class
* quantiles

@MarionLi0 : do you agree ?

**Comment by MarionLi0** [comment]
sizeClass instead of nbDaysInClass?
Agreed @baptsegu

**Comment by baptsegu** [comment]
Hmmm... bon ok @MarionLi0

**Comment by baptsegu** [comment]
Merci :)
