### ISSUE TITLE
getProbability: levelsProba - Identification of levels for each variable in each season

### ISSUE THREAD

**Issue by MarionLi0** [rte-antares-rpackage/flowBasedClustering#37]
levelsProba must now be able to describe different levels for one variable in different seasons.
To do so, levelsProba is now a list (seasons = list (variables = c(levels) ) )
example:
```
levelsProba <- list(
winterWd = list(FR_LOAD = c(1/3, 2/3), DE_WIND = c(1/3, 2/3)),
interSeasonWd = list(FR_LOAD = c(1/3, 2/3), DE_WIND = c(1/3, 2/3), DE_SOLAR = c(1/2)),
SummerWd= list(FR_LOAD = c(1/2), DE_WIND = c(1/3, 2/3), DE_SOLAR = c(1/2)))
```

Particular cases:
if an existing variable is not quoted in one season (example SOLAR_DE in winterWd), default value is NULL
if an existing season is not quoted (example SummerWe), all values are NULL.

Error returned when:
```
levelsProba <- list(
FR_LOAD = c(1/3, 2/3), DE_WIND = c(1/3, 2/3),
)
```
-> Old syntax: the season must be specified. Error: "Names of the list levelsProba should be classes of the clustering (here: unique(cluster$Class) )"
```
levelsProba <- list(
summerWd = c(1/3, 2/3)
)
```
-> The variables must be differenciated in each season. Error: "A list of variables is expected in each class of levelsProba (here : names(climate) )"
```
levelsProba <- list(
winterWd = list(FR_LAOD = c(1/3, 2/3), DE_WIND = c(1/3, 2/3))
)
```
-> Error: "FR_LAOD is not a variable of the climate input."

Help/Description of the function:
```
levelsProba <- list(
winterWd = list(FR_LOAD = c(1/3, 2/3), DE_WIND = c(1/3, 2/3)),
interSeasonWd = list(FR_LOAD = c(1/3, 2/3), DE_WIND = c(1/3, 2/3), DE_SOLAR = c(1/3, 2/3)),
SummerWd= list(FR_LOAD = c(1/3, 2/3), DE_WIND = c(1/3, 2/3), DE_SOLAR = c(1/3, 2/3))
```

**Comment by MarionLi0** [comment]
see #36

**Comment by baptsegu** [comment]
Pour les trois cas d'erreur décrits dans l'issue, merci d'utiliser les même messages d'erreur

**Comment by baptsegu** [comment]
ok
