### ISSUE TITLE
plotFlowbased

### ISSUE THREAD

**Issue by MarionLi0** [rte-antares-rpackage/flowBasedClustering#6]
input : PTDF : changer le nom de la colonne RAM_0 en RAM (dans la fonction et l'exemple) et préciser dans la doc que le data.frame attendu doit avoir pour colonne au moins BE, DE, FR, NL et RAM

Visualisation: le graphe est rectangulaire (export donne un grand rectangle blanc sous l'image), faire qu'il occupe tout l'espace (plus "carré")
![l3 be-fr](https://user-images.githubusercontent.com/24607174/27140280-6c716a4e-5125-11e7-9ccd-92085451d323.png)

Limite des axes (+/-7000, +/-10000): il y a des domaines qui dépassent les 7000, donc mettre par défaut à 10000 partout et permettre de choisir les limites d'axes dans la fonction.

Merci=)

**Comment by baptsegu** [comment]
Note : le fichier en input doit prendre en nom de colonne ou RAM **ou** RAM_0 (pour éviter les régressions)

**Comment by TitouanRobert** [comment]
Terminé, arguments xlim et ylim ajoutés (par défaut à 10000). Remplacement de RAM_0 par RAM

**Comment by baptsegu** [comment]
LA fonction doit pouvoir gérer les deux noms de colonne. RAM_0 et RAM.

**Comment by TitouanRobert** [comment]
Oui c'est géré de mon côté

**Comment by TitouanRobert** [comment]
J'ai ajouté le même traitement dans l'autre package (antaresFlowbased)

**Comment by baptsegu** [comment]
![image](https://user-images.githubusercontent.com/23483145/31709323-f3a26692-b3f1-11e7-961a-c4c0ff28cc9d.png)
Graphe toujours carré chez moi

**Comment by bthieurmel** [comment]
J'ai rajouté deux arguments ``width`` et ``height`` dans ``plotFlowbased`` et ``clusterPlot``, avec des valeurs par défaut.

On peut cependant repasser en graphique avec taille dynamique en mettant par exemple ``heigth = '400px', width = '100%'``

**Comment by baptsegu** [comment]
`plotFlowBased` : testé et OK
`clusterPlot` : testé et OK !

merci Benoit
